server:
  port: 9001
spring:
  application:
    name: ps-api
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/  
      
#整合Spring Security实现访问API页面输入用户名密码 ,enabled:true开启        
security:
  basic:
    path: /swagger-ui.html
    enabled: false
  user:
    name: lvjh
    password: 123456   