server:
  port: 8002
  tomcat:
    uri-encoding: UTF-8  
spring:
  application:
    name: os-service
#mongo配置    
  data:
    mongodb:
      primary: 
        host: localhost
        port: 27017
        database: sc-db
      secondary:
        host: localhost
        port: 27017
        database: sc-test
#redis配置        
  redis:
    # Redis数据库索引（默认为0）
    database: 10
    # Redis服务器地址
    host: localhost
    # 连接池最大连接数（使用负值表示没有限制）
    max-active: 8
    # 连接池中的最大空闲连接
    max-idle: 8
    # 连接池最大阻塞等待时间（使用负值表示没有限制）
    max-wait: -1
    # 连接池中的最小空闲连接
    min-idle: 0
    #如果有密码
    password: 
    # Redis服务器连接端口
    prot: 6379          
  aop:
    auto: true
    proxy-target-class: true    
#整合Spring Security实现访问API页面输入用户名密码           
security:
  basic:
    path: /swagger-ui.html
    enabled: false
  user:
    name: lvjh
    password: 123456  
feign:
  hystrix:
    enabled: true             
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
