spring:
  application:
    name: auth-server

#eureka:
#  instance:
#    nonSecurePort: 9100
#  client:
#    service-url:
#      defaultZone: http://10.10.100.125:7000/eureka
## Define the port where the UAA server would be running
#server:
#  port: 9100
#  # Use different context-path to avoid session cookie overlapping
#  context-path: /uaa
#  use-forward-headers: true
