spring:
  profiles: test
  thymeleaf.cache: false
  aop:
    auto: true
   
eureka:
  instance: 
    preferIpAddress: true
    nonSecurePort: 9100
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/      
      
logging:
  level.org.springframework.security: DEBUG
 
#authprop: 
#  allowOrigin: .gfresh.cn,//gfresh.cn,.igfresh.com
#  zuulIp: 10.10.100.125
#  zuulPort: 9000
#  zuulDns: 10.10.100.125
#  scheme: http