
server:
  port: 8761
spring:
  application:
    name: sc-eureka-server
eureka:
  client:
    #并不自注册,防止自己注册自己
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://localhost:${server.port}/eureka/
